sudo: required

services:
 - docker
 
before_install:
 - docker build -t sujoydipta/react-test -f ./client/Dockerfile.dev ./client
 
script:
 - docker run -e CI=true sujoydipta/react-test npm run test
 
after_success:
 - docker build -t sujoydipta/multi-client ./client
 - docker build -t sujoydipta/multi-server ./server
 - docker build -t sujoydipta/multi-worker ./worker
 - docker build -t sujoydipta/multi-nginx ./nginx
  
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
 - docker push sujoydipta/multi-client
 - docker push sujoydipta/multi-server
 - docker push sujoydipta/multi-worker
 - docker push sujoydipta/multi-nginx
 
deploy:
  edge: true  
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket-name: elasticbeanstalk-us-east-1-078102778856
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  
 
  